aroundMedian: aroundMedian.cpp
	g++ -g -std=c++11 -Wall -o aroundMedian aroundMedian.cpp

test:
	# -------test case-------
	cat testcase.txt
	#
	# -------result output-------
	./aroundMedian < testcase.txt

clean:
	rm aroundMedian
