bipartite: bipartite.cpp
	g++ -g -std=c++11 -Wall -o bipartite bipartite.cpp

test:
	# -------test case-------
	cat testcase.txt
	#
	# -------result output-------
	./bipartite < testcase.txt

clean:
	rm bipartite
