reverse: reverse.cpp
	g++ -g -std=c++11 -Wall -o reverse reverse.cpp

test:
	# -------test case-------
	cat testcase.txt
	#
	# -------result output-------
	./reverse < testcase.txt

clean:
	rm reverse
