tripleSum: tripleSum.cpp
	g++ -g -std=c++11 -Wall -o tripleSum tripleSum.cpp

test:
	# -------test case-------
	cat testcase.txt
	#
	# -------result output-------
	./tripleSum < testcase.txt

clean:
	rm tripleSum
