binaryTree: binaryTree.cpp
	g++ -g -std=c++11 -Wall -o binaryTree binaryTree.cpp

test:
	# -------test case-------
	cat testcase.txt
	#
	# -------result output-------
	./binaryTree < testcase.txt

clean:
	rm binaryTree
