DynamicMedian: DynamicMedian.cpp
	g++ -g -std=c++11 -Wall -o DynamicMedian DynamicMedian.cpp

test:
	# -------test case-------
	cat testcase.txt
	#
	# -------result output-------
	./DynamicMedian < testcase.txt

clean:
	rm DynamicMedian
