searchPair: searchPair.cpp
	g++ -g -std=c++11 -Wall -o searchPair searchPair.cpp

test:
	# -------test case-------
	cat testcase.txt
	#
	# -------result output-------
	./searchPair < testcase.txt

clean:
	rm searchPair
