cutvertex: cutvertex.cpp
	g++ -g -std=c++11 -Wall -o cutvertex cutvertex.cpp

test:
	# -------test case-------
	cat testcase.txt
	#
	# -------result output-------
	./cutvertex < testcase.txt

clean:
	rm cutvertex
