scheduling: scheduling.cpp
	g++ -g -std=c++11 -Wall -o scheduling scheduling.cpp

test:
	# -------test case-------
	cat testcase.txt
	#
	# -------result output-------
	./scheduling < testcase.txt

clean:
	rm scheduling
